"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "socialia",
        skip_rules=(
            # Structural / README debt — socialia ships a deep top-level
            # layout (16 .py files, twitter_* cluster) and a README that
            # doesn't follow the current SciTeX template. Tracked as a
            # whole-package overhaul; piecemeal fixes leave the directory
            # half-organized, per the PS-108 hint.
            "PS-106",
            "PS-107",
            "PS-108",
            "PS-108b",
            "PS-109",
            "PS-110",
            "PS-112",
            "PS-116",  # README banned-buzzword (deprecated `Interfaces:` callout)
            "PS-122",  # docs.yml CI workflow missing
            "PS-128",  # .gitignore excludes _sphinx_html (must be tracked)
            "PS-141",  # README missing `## Demo`
            "PS-142",  # README missing `## Architecture`
            "PS-501",  # example main() not @stx.session-decorated
            # Test-tree mirror — every test_*.py at tests/ root is a flat
            # behavioural test. Migration to tests/socialia/<...>/ requires
            # renaming several files to match private/public conventions
            # (PS-205) AND filling now-empty mirror dirs with real tests.
            # Defer to a single coherent migration commit.
            "PS-201",
            "PS-202",
            "PS-203",
            "PS-204",
            "PS-205",
            "PS-207",
            # MCP / Python-API parity gap.
            "§6",
            # CLI: noun catalog + audit-cli §-rules need full overhaul
            # alongside the source-tree reorg.
            "§1d",
            "§1a",
            "§1",
            "§2",
            "§4",
            "§5",  # missing skills_list / skills_get MCP tools
            "§10",  # cold-start import time over threshold
        ),
    )
